spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/simpson-database
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}

server:
  port: 8081


